typedef char xt_s8;
typedef unsigned char xt_u8;
typedef short xt_s16;
typedef unsigned short xt_u16;
typedef int xt_s32;
typedef unsigned int xt_u32;
typedef long long xt_s64;
typedef char * xt_string;
typedef unsigned char xt_bool;
typedef void xt_void;
typedef float xt_float;
typedef double xt_double;